import { useRef, useState } from 'react'
import { useDemo } from '../demo/context'
import { gifts, products, timeText, today, uid } from '../demo/data'
import { cartTotal, checkIn, redeemGift, stockRemaining } from '../demo/commerce'
import { Button, Card, Confirm, DemoStates, Empty, Field, Note, Page, Row, StateView, Tabs } from './UI'

export default function Shop({ path }) {
  const {state,update,navigate,notify}=useDemo()
  const [,page,id]=path.split('/')
  const [filter,setFilter]=useState('全部')
  const [variant,setVariant]=useState(0)
  const [qty,setQty]=useState(1)
  const [addressId,setAddressId]=useState('')
  const [couponId,setCouponId]=useState('')
  const [payment,setPayment]=useState('成功')
  const [mode,setMode]=useState('正常')
  const [reason,setReason]=useState('商品问题')
  const [description,setDescription]=useState('')
  const submitted=useRef(false)
  const [now] = useState(() => Date.now())
  const address=state.addresses.find(a=>a.id===addressId)||state.addresses.find(a=>a.default)||state.addresses[0]
  const subtotal=cartTotal(state.cart)
  const coupons=state.coupons.filter(c=>!c.used && c.expires>now && subtotal>=c.minimum)
  const coupon=coupons.find(c=>c.id===couponId)
  const total=Math.max(0,subtotal-(coupon?.amount||0))
  const product=products.find(p=>p.id===id)
  const addCart=(p,buy=false)=>{
    const count=state.cart.filter(i=>i.product===p.id).reduce((n,i)=>n+i.qty,0)
    if(qty+count>stockRemaining(state,p.id)) {notify('超出模拟库存，请调整数量');return}
    const key=`${p.id}-${variant}`
    update(s=>({...s,cart:s.cart.some(i=>i.id===key)?s.cart.map(i=>i.id===key?{...i,qty:i.qty+qty}:i):[...s.cart,{id:key,product:p.id,variant:p.variants[variant],qty}]}))
    if(buy) navigate('shop/checkout'); else notify('已加入购物袋')
  }
  const checkout=()=>{
    if(submitted.current || !state.cart.length || !address) return
    if(state.cart.some(i=>state.cart.filter(x=>x.product===i.product).reduce((n,x)=>n+x.qty,0)>stockRemaining(state,i.product))) {notify('库存不足，请返回购物袋调整');return}
    submitted.current=true
    const orderId=uid()
    update(s=>!s.cart.length?s:{...s,orders:[{id:orderId,type:'cash',status:'待支付',items:s.cart.map(i=>({...i,name:products.find(p=>p.id===i.product).name})),date:Date.now(),subtotal,total,discount:coupon?.amount||0,coupon:coupon?.id,address:{...address}},...s.orders],cart:[],coupons:s.coupons.map(c=>c.id===coupon?.id?{...c,used:true}:c)})
    navigate(`shop/pay/${orderId}`)
  }
  if(page==='product') {
    if(!product) return <Page title="这件好物暂时不在。"><Button onClick={()=>navigate('shop')}>回到小店</Button></Page>
    const stock=stockRemaining(state,id)
    return <Page title={product.name} eyebrow="A LITTLE GIFT TO YOURSELF" intro={product.desc}><div className={`product-hero ${product.color}`}><img src={`/icons/${product.icon}`} alt={product.name}/><span>VIVI LITTLE STORE</span></div><div className="price-line"><strong>¥ {product.price.toFixed(2)}</strong><span>模拟价格 · 剩余 {stock} 件</span></div><Field label="选择规格"><select value={variant} onChange={e=>setVariant(Number(e.target.value))}>{product.variants.map((v,i)=><option value={i} key={v}>{v}</option>)}</select></Field><Field label="数量"><input type="number" min="1" max={Math.max(1,stock)} value={qty} onChange={e=>setQty(Math.max(1,Math.min(stock||1,Number(e.target.value)||1)))}/></Field><Card><h2>关于这份小心意</h2><p>{product.parts.length?`演示目录部位：${product.parts.join('、')}`:'配套工具，无操作计时配置。'}</p><p>商品名称、型号、价格均为前端示例。真实适用范围与用法以正式产品资料为准。</p></Card><div className="button-pair"><Button secondary disabled={!stock} onClick={()=>addCart(product)}>加入购物袋</Button><Button disabled={!stock} onClick={()=>addCart(product,true)}>模拟购买</Button></div>{product.duration&&<Button secondary onClick={()=>{if(state.flow.startedAt&&!state.flow.saved){navigate(state.flow.endedAt?'trim/care':'trim/timer');return}update(s=>({...s,flow:{...s.flow,product:product.id,checks:[],instructionsRead:null,skinPhoto:null,saved:false,startedAt:null,endedAt:null,uncomfortable:false,feeling:'',effect:'',note:'',id:uid()}}));navigate('trim/prepare')}}>我已购买，开始使用</Button>}<Row title="查看购物袋" subtitle={`${state.cart.reduce((n,i)=>n+i.qty,0)} 件好物`} onClick={()=>navigate('shop/cart')}/></Page>
  }
  if(page==='cart') return <Page title="我的小小购物袋。" intro="给自己挑一点喜欢的。">{state.cart.length ? <>{state.cart.map(item=>{const p=products.find(x=>x.id===item.product);return <Card key={item.id}><div className="product-line"><img src={`/icons/${p.icon}`} alt=""/><div><h2>{p.name}</h2><p>{item.variant}</p><strong>¥ {p.price}</strong></div></div><div className="quantity-row"><button aria-label={`减少${p.name}数量`} disabled={item.qty<=1} onClick={()=>update(s=>({...s,cart:s.cart.map(i=>i.id===item.id?{...i,qty:i.qty-1}:i)}))}>−</button><span>{item.qty}</span><button aria-label={`增加${p.name}数量`} disabled={state.cart.filter(i=>i.product===p.id).reduce((n,i)=>n+i.qty,0)>=stockRemaining(state,p.id)} onClick={()=>update(s=>({...s,cart:s.cart.map(i=>i.id===item.id?{...i,qty:i.qty+1}:i)}))}>＋</button><button className="remove-item" onClick={()=>update(s=>({...s,cart:s.cart.filter(i=>i.id!==item.id)}))}>移除</button></div></Card>})}<div className="price-line"><span>合计</span><strong>¥ {subtotal.toFixed(2)}</strong></div><Button onClick={()=>navigate('shop/checkout')}>去确认订单</Button></>:<Empty title="购物袋还轻轻的。" text="去小店逛逛，看看有没有喜欢的。"><Button onClick={()=>navigate('shop')}>逛逛小店</Button></Empty>}</Page>
  if(page==='checkout') return <Page title="确认这份小心意。" intro="当前为模拟订单，不会实际付款或寄送。">{!state.cart.length?<Empty title="还没有选好商品。"><Button onClick={()=>navigate('shop')}>去小店看看</Button></Empty>:<><Field label="收货地址"><select value={address?.id||''} onChange={e=>setAddressId(e.target.value)}><option value="" disabled>请选择地址</option>{state.addresses.map(a=><option key={a.id} value={a.id}>{a.name} · {a.detail}</option>)}</select></Field><Row title="管理收货地址" onClick={()=>navigate('profile/addresses')}/><Card>{state.cart.map(i=><div className="receipt-row" key={i.id}><span>{products.find(p=>p.id===i.product).name} × {i.qty}<small>{i.variant}</small></span><strong>¥ {products.find(p=>p.id===i.product).price*i.qty}</strong></div>)}</Card><Field label="优惠券"><select value={coupon?.id||''} onChange={e=>setCouponId(e.target.value)}><option value="">不使用优惠券</option>{coupons.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Card><div className="receipt-row"><span>商品金额</span><span>¥ {subtotal}</span></div><div className="receipt-row"><span>运费（模拟免邮）</span><span>¥ 0</span></div><div className="receipt-row"><span>优惠</span><span>− ¥ {coupon?.amount||0}</span></div><div className="receipt-row"><strong>实付合计</strong><strong>¥ {total.toFixed(2)}</strong></div></Card><Button disabled={!address} onClick={checkout}>创建模拟订单</Button></>}</Page>
  if(page==='pay'||page==='order'||page==='aftersale'||page==='logistics') {
    const order=state.orders.find(o=>o.id===id)
    if(!order)return <Page title="没有找到这份订单。"><Button onClick={()=>navigate('shop/orders')}>查看我的订单</Button></Page>
    if(page==='pay') return <Page title="最后一步，模拟支付。" intro="不会连接支付平台，也不会发生扣款。"><div className="payment-total">¥ {order.total.toFixed(2)}<small>{order.status}</small></div>{order.status==='待支付'?<><Field label="选择演示支付结果"><select value={payment} onChange={e=>setPayment(e.target.value)}>{['成功','取消','失败','处理中'].map(p=><option key={p}>{p}</option>)}</select></Field><Button onClick={()=>{update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:payment==='成功'?'待发货':payment==='处理中'?'支付处理中':'待支付',payment}:o)}));notify(`模拟支付${payment}`);navigate(`shop/order/${id}`)}}>确认模拟支付</Button></>:<Button onClick={()=>navigate(`shop/order/${id}`)}>查看订单状态</Button>}</Page>
    if(page==='aftersale') return <Page title="我们听听你的情况。" intro="这是一份本地售后申请演示。"><Field label="售后原因"><select value={reason} onChange={e=>setReason(e.target.value)}>{['商品问题','配送问题','其他问题'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="情况说明"><textarea value={description} maxLength={500} onChange={e=>setDescription(e.target.value)} placeholder="请简单描述遇到的情况"/></Field><Button disabled={!description.trim()||!!order.aftersale} onClick={()=>{update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,aftersale:{reason,description,status:'模拟受理中'}}:o)}));notify('已记录本地售后申请');navigate(`shop/order/${id}`)}}>{order.aftersale?'申请已记录':'提交模拟申请'}</Button></Page>
    if(page==='logistics') return <Page title="好物正在路上。" intro="物流时间与节点为演示内容。"><Card><h2>{order.status==='待发货'?'小店正在打包':'小羊快递 · DEMO-202609'}</h2><p>{order.address?.detail}</p></Card><div className="timeline">{(order.status==='已完成'?['已签收','配送中','已发出','订单已确认']:order.status==='待收货'?['配送中','已发出','订单已确认']:['订单已确认，等待发货']).map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></Page>
    return <Page title={order.status==='待发货'?'心意已确认。':'我的这份小心意。'} intro={`订单 ${order.id.slice(0,8)} · ${timeText(order.date)}`}><Card color="green"><h2>{order.status}</h2>{order.payment&&<p>模拟支付结果：{order.payment}</p>}{order.aftersale&&<p>售后：{order.aftersale.status}</p>}</Card><Card>{order.type==='gift'?<h2>{order.name} · {order.cost} 金毛</h2>:order.items.map(i=><div className="receipt-row" key={i.id}><span>{i.name}<small>{i.variant}</small></span><span>× {i.qty}</span></div>)}<p>{order.address?.name} · {order.address?.phone}</p><p>{order.address?.detail}</p><strong>{order.type==='gift'?'金毛兑换订单':`实付 ¥ ${order.total.toFixed(2)}`}</strong></Card>{order.status==='待支付'&&<><Button onClick={()=>navigate(`shop/pay/${id}`)}>继续模拟支付</Button><Confirm label="取消订单" message="取消这份模拟订单？已使用的优惠券会退回。" onConfirm={()=>update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:'已关闭'}:o),coupons:s.coupons.map(c=>c.id===order.coupon?{...c,used:false}:c)}))}/></>}{order.status==='支付处理中'&&<><Note>结果尚未确认，不会当作已付款；请查询原订单。</Note><Button onClick={()=>{update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:'待发货',payment:'成功'}:o)}));notify('演示查询结果：支付成功')}}>模拟查询支付结果</Button></>}{['待发货','待收货','已完成'].includes(order.status)&&<><Row title="查看模拟物流" onClick={()=>navigate(`shop/logistics/${id}`)}/><Row title="申请售后" onClick={()=>navigate(`shop/aftersale/${id}`)}/></>}{order.status==='待收货'&&<Button onClick={()=>update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:'已完成'}:o)}))}>确认模拟收货</Button>}{order.status==='待发货'&&<details className="demo-controls"><summary>推进演示物流</summary><Button secondary onClick={()=>update(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,status:'待收货'}:o)}))}>模拟发货</Button></details>}</Page>
  }
  if(page==='orders') {
    const items=state.orders.filter(o=>filter==='全部'||o.status===filter)
    return <Page title="我的好物行程。"><Tabs items={['全部','待支付','待发货','待收货','已完成','已关闭']} value={filter} onChange={setFilter}/>{items.length?items.map(o=><Card key={o.id}><div className="receipt-row"><strong>{o.type==='gift'?o.name:o.items[0]?.name}</strong><span>{o.status}</span></div><p>{timeText(o.date)}</p><Button secondary onClick={()=>navigate(`shop/order/${o.id}`)}>查看订单</Button></Card>):<Empty text="这个分类还没有订单。"/>}</Page>
  }
  if(page==='ledger') return <Page title="一根一根，慢慢攒。" intro="金毛明细只记录商城和作品权益。"><div className="balance-card"><div><p>我的金毛</p><strong>{state.balance}<span> 金毛</span></strong></div><img src="/icons/10-rewards.png" alt=""/></div><details className="module-card"><summary>金毛规则</summary><p>演示到访打卡每日 +1；作品按效率兑换；兑换商品会扣减金毛。当前演示金毛不设有效期，不可充值或提现。</p></details>{state.ledger.map(item=><div className="ledger-row" key={item.id}><span>{item.title}<small>{timeText(item.date)}</small></span><strong>{item.amount>0?'+':''}{item.amount}</strong></div>)}</Page>
  if(page==='coupons') return <Page title="口袋里的小惊喜。" intro="优惠券仅用于模拟订单。">{state.coupons.length?state.coupons.map(c=><Card color="yellow" key={c.id}><h2>{c.name}</h2><p>满 ¥{c.minimum} 可用 · {c.used?'已使用':c.expires<now?'已过期':'可使用'}</p><small>有效期至 {new Date(c.expires).toLocaleDateString('zh-CN')}</small></Card>):<Empty text="用金毛去兑换一张小小心意吧。"><Button onClick={()=>navigate('shop/rewards')}>看看可兑换好物</Button></Empty>}</Page>
  if(page==='redemptions') return <Page title="金毛换来的小心意。">{state.redemptions.length?state.redemptions.map(r=><Row key={r.id} title={r.name} subtitle={`${r.cost} 金毛 · ${timeText(r.date)}`} onClick={()=>navigate(r.gift==='coupon'?'shop/coupons':`shop/order/${r.id}`)}/>):<Empty text="兑换过的好物会留在这里。"/>}</Page>
  if(page==='reward') {
    const gift=gifts.find(g=>g.id===id)
    if(!gift)return <Page title="没有找到这份礼物。"><Button onClick={()=>navigate('shop/rewards')}>返回好物</Button></Page>
    const available=state.redemptions.filter(r=>r.gift===id).length<gift.stock
    return <Page title={gift.name} intro={gift.desc}><div className="product-hero yellow"><img src={`/icons/${gift.icon}`} alt=""/></div><div className="price-line"><strong>{gift.cost} 金毛</strong><span>余额 {state.balance}</span></div>{id!=='coupon'&&<><Field label="演示收货地址"><select value={address?.id||''} onChange={e=>setAddressId(e.target.value)}><option value="" disabled>请选择</option>{state.addresses.map(a=><option key={a.id} value={a.id}>{a.name} · {a.detail}</option>)}</select></Field><Row title="管理地址" onClick={()=>navigate('profile/addresses')}/></>}<Note>{!available?'已达到演示限兑数量。':state.balance<gift.cost?'金毛还差一点点，不着急。':'兑换成功后会扣减对应金毛，运费为模拟免邮。'}</Note><Button disabled={!available||state.balance<gift.cost||(id!=='coupon'&&!address)} onClick={()=>{update(s=>redeemGift(s,id,address?.id,now));notify('兑换完成，已更新模拟余额');navigate('shop/redemptions')}}>确认兑换</Button></Page>
  }
  if(page==='rewards') return <Page title="把小积攒，换成小喜欢。" intro={`当前可用 ${state.balance} 金毛`}><Row title="我的优惠券" onClick={()=>navigate('shop/coupons')}/><Row title="兑换记录" onClick={()=>navigate('shop/redemptions')}/>{gifts.map(g=><Card key={g.id}><div className="product-line"><img src={`/icons/${g.icon}`} alt=""/><div><h2>{g.name}</h2><p>{g.desc}</p><strong>{g.cost} 金毛</strong></div></div><Button secondary onClick={()=>navigate(`shop/reward/${g.id}`)}>看看这份好物</Button></Card>)}</Page>
  return <Page title="给自己的小心意。" eyebrow="LITTLE THINGS, BIG JOY" intro="把日常照顾，变成值得期待的小事。"><div className="balance-card"><div><p>我的金毛</p><strong>{state.balance} <span>金毛</span></strong><button className="text-button" onClick={()=>navigate('shop/ledger')}>看看明细 ↗</button></div><img src="/icons/10-rewards.png" alt=""/></div><div className="checkin-bar"><p>每天来坐坐，就很好。<small>到访打卡，无需每天脱毛</small></p><button disabled={state.checkin===today()} onClick={()=>{update(s=>checkIn(s));notify('今天的到访记下了，+1 模拟金毛')}}>{state.checkin===today()?'今日已打卡':'打卡 +1'}</button></div><div className="shop-shortcuts"><Row title="金毛好物" onClick={()=>navigate('shop/rewards')}/><Row title="购物袋" subtitle={`${state.cart.reduce((n,i)=>n+i.qty,0)} 件`} onClick={()=>navigate('shop/cart')}/><Row title="我的订单" onClick={()=>navigate('shop/orders')}/></div><h2 className="subheading">逛逛小店</h2><Tabs items={['全部','脱毛产品','护理产品','配套工具']} value={filter} onChange={setFilter}/><DemoStates onChange={setMode}/>{mode!=='正常'?<StateView mode={mode} retry={()=>setMode('正常')}/>:<div className="product-grid">{products.filter(p=>filter==='全部'||p.category===filter).map(p=><button className="product-card" key={p.id} onClick={()=>navigate(`shop/product/${p.id}`)}><div className={`product-art ${p.color}`}><img src={`/icons/${p.icon}`} alt=""/><span>VIVI LITTLE STORE</span></div><h3>{p.name}</h3><p>{p.desc}</p><strong>¥ {p.price}</strong></button>)}</div>}</Page>
}
