import { useState } from 'react'
import { useDemo } from '../demo/context'
import { uid, timeText } from '../demo/data'
import { Button, Card, Confirm, DemoStates, Empty, Field, Note, Page, Row, StateView, Tabs } from './UI'

export default function Tree({ path, onCompose, onEdit }) {
  const { state, update, navigate, notify } = useDemo()
  const [, page, id] = path.split('/')
  const [filter, setFilter] = useState('全部')
  const [count, setCount] = useState(3)
  const [mode, setMode] = useState('正常')
  const [comment, setComment] = useState('')
  const [report, setReport] = useState('包含个人信息')
  const [reportNote, setReportNote] = useState('')
  const post = state.posts.find(p => p.id === id)
  const like = id => update(s => ({ ...s, liked:s.liked.includes(id) ? s.liked.filter(x => x !== id) : [...s.liked,id] }))
  const remove = id => { update(s => ({ ...s, posts:s.posts.filter(p => p.id !== id), comments:s.comments.filter(c => c.post !== id) })); notify('这条笔记已从本地演示中删除'); navigate('tree/mine') }
  const review = (id, status) => update(s => ({ ...s, posts:s.posts.map(p => p.id === id ? {...p,status} : p) }))
  const renderPost = p => <article className={`post-card ${p.color || 'pink'}`} key={p.id}><div className="post-meta"><span>一只匿名小羊</span><span>{p.own ? p.status : p.category}</span></div><button className="post-open" onClick={() => navigate(`tree/detail/${p.id}`)}><h2>{p.title}</h2><p className="note-body">{p.body}</p>{p.images?.length > 0 && <div className="note-images">{p.images.map(image => <img key={image.id} src={image.url} alt={image.name} loading="lazy" />)}</div>}</button><div className="post-foot"><span>{p.tags?.join(' · ') || p.category}</span><button className="like-button" aria-label={`抱抱：${p.title}`} aria-pressed={state.liked.includes(p.id)} onClick={() => like(p.id)}>{state.liked.includes(p.id) ? '♥' : '♡'} {p.likes + Number(state.liked.includes(p.id))}</button></div></article>
  if (page === 'mine') return <Page title="我留在树洞的话。" intro="自己的笔记、审核进度和收到的回应。"><Button onClick={onCompose}>写一篇新的笔记 ↗</Button>{state.posts.filter(p => p.own).length ? <div className="post-list">{state.posts.filter(p => p.own).map(p => <div key={p.id}>{renderPost(p)}{p.status === '未通过' && <Note>演示原因：内容需要补充或修改，请检查个人信息后重新提交。</Note>}<div className="button-pair"><Button secondary onClick={() => onEdit(p)}>编辑笔记</Button><Confirm label="删除笔记" message="删除这条本地笔记及其回应？" onConfirm={() => remove(p.id)} /></div>{p.status === '待审核' && <details className="demo-controls"><summary>模拟内容审核结果</summary><div className="button-pair"><Button secondary onClick={() => review(p.id,'已发布')}>演示审核通过</Button><Button secondary onClick={() => review(p.id,'未通过')}>演示审核未通过</Button></div></details>}</div>)}</div> : <Empty text="写下第一个小心情，它会出现在这里。" />}</Page>
  if (page === 'detail' || page === 'report') {
    if (!post || state.hidden.includes(id) || (post.status !== '已发布' && !post.own)) return <Page title="这条内容暂时不可见。"><Empty text="它可能已被删除，或尚未发布。" /><Button onClick={() => navigate('tree')}>回到树洞</Button></Page>
    if (page === 'report') return <Page title="让树洞保持温柔。" intro="举报信息仅用于演示，不会发送给任何人。"><Card><h2>{post.title}</h2></Card><Field label="举报原因"><select value={report} onChange={e => setReport(e.target.value)}>{['包含个人信息','令人不适的内容','广告或误导信息','其他'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="补充说明（可选）"><textarea value={reportNote} maxLength={300} onChange={e => setReportNote(e.target.value)} /></Field><Button onClick={() => { update(s => ({ ...s, reports:[...s.reports,{ id:uid(), post:id, reason:report, note:reportNote }] })); notify('举报已记录在本地演示中'); navigate(`tree/detail/${id}`) }}>提交演示举报</Button></Page>
    return <Page title={post.title} eyebrow="A LITTLE VOICE, HEARD" intro={`一只匿名小羊 · ${timeText(post.date)} · ${post.status}`}><Card color={post.color}><p className="note-body">{post.body}</p>{post.images?.length > 0 && <div className="detail-images">{post.images.map(image => <img key={image.id} src={image.url} alt={image.name} />)}</div>}<Note>{post.tags?.join(' · ')}</Note></Card><Note>树洞内容是个人经验与心情，不替代正式产品说明。</Note><div className="button-pair"><Button secondary onClick={() => like(id)}>{state.liked.includes(id) ? '♥ 已抱抱' : '♡ 给一个抱抱'}</Button>{!post.own && <Button secondary onClick={() => navigate(`tree/report/${id}`)}>举报内容</Button>}</div>{post.own ? <Row title="查看我的笔记与审核状态" onClick={() => navigate('tree/mine')} /> : <Confirm label="隐藏这条内容" message="之后不再在本地树洞列表显示这条内容？" onConfirm={() => { update(s => ({...s,hidden:[...s.hidden,id]})); navigate('tree') }} />}<h2 className="subheading">树荫下的回应</h2>{state.comments.filter(c => c.post === id).map(c => <Card key={c.id}><small>{c.own ? '我（匿名）' : '路过的小羊'} · {timeText(c.date)}</small><p className="note-body">{c.body}</p>{c.own && <Confirm label="删除我的回应" message="删除这条本地回应？" onConfirm={() => update(s => ({ ...s, comments:s.comments.filter(x => x.id !== c.id) }))} />}</Card>)}{!state.comments.some(c => c.post === id) && <Note>暂时还没有回应，留一句温柔的话吧。</Note>}{post.status === '已发布' && <form onSubmit={e => { e.preventDefault(); if (!comment.trim()) return; update(s => ({ ...s, comments:[...s.comments,{id:uid(),post:id,body:comment.trim(),own:true,date:Date.now()}] })); setComment(''); notify('已添加匿名回应') }}><Field label="匿名回应"><textarea value={comment} maxLength={300} onChange={e => setComment(e.target.value)} placeholder="轻轻说一句…" required /></Field><Button type="submit" disabled={!comment.trim()}>留下回应</Button></form>}</Page>
  }
  const filtered = state.posts.filter(p => p.status === '已发布' && !state.hidden.includes(p.id) && (filter === '全部' || filter === '大家的状态' ? filter === '全部' || p.category !== '问问题' : p.category === filter))
  return <Page title="心事，轻轻放。" eyebrow="A SOFT PLACE TO LAND" intro="这里有一片小小树荫，接住每一种心情。"><div className="tree-banner"><img src="/icons/树洞.svg" alt="" /><p>不用介绍自己，<br /><strong>做一只自由的小羊就好。</strong></p><button className="compose-entry" aria-label="发布图文笔记" onClick={onCompose}><img src="/icons/发布.svg" alt="" /></button></div><Tabs items={['全部','问问题','大家的状态','小小建议']} value={filter} onChange={x => { setFilter(x);setCount(3) }} /><div className="list-toolbar"><button onClick={() => navigate('tree/mine')}>我的笔记 ↗</button><button onClick={() => { setMode('正常');setCount(3);notify('演示内容已刷新') }}>刷新 ↻</button></div><DemoStates onChange={setMode} />{mode !== '正常' ? <StateView mode={mode} retry={() => setMode('正常')} /> : <><div className="post-list">{filtered.slice(0,count).map(renderPost)}</div>{filtered.length === 0 && <Empty text="这里暂时没有笔记，写下第一句吧。" />}{count < filtered.length && <Button secondary onClick={() => setCount(n => n+3)}>再看看更多心情</Button>}</>}</Page>
}
